### ISSUE TITLE
Allow building using Ninja and with ZTH_HAVE_LIBZMQ=OFF

### ISSUE THREAD

**Issue by windelbouwman** [jhrutgers/zth#6]
When building with `cmake -G Ninja ..` I ran into some troubles, also building with `ZTH_HAVE_LIBZMQ=OFF` results in some build errors.

What would you like me to do? Submit a pull request for this? Add a CI job for this specific configuration?

**Comment by jhrutgers** [comment]
Should have been fixed on master (838cb47) now.
